Create database per3_npm
use per3_npm

SELECT * FROM EMP;
SELECT * FROM DEPT;
SELECT * FROM BONUS;
SELECT * FROM SALGRADE;

--1
SELECT E.ENAME, D.DNAME
FROM EMP E
LEFT JOIN DEPT D
ON E.DEPTNO = D.DEPTNO;

--2
SELECT E.ENAME, D.DNAME
FROM EMP As E
inner JOIN DEPT As D
ON E.DEPTNO = D.DEPTNO;

--3
SELECT 
    EMP1.ENAME AS Nama_Karyawan, 
    EMP1.SAL AS Gaji_Tertinggi, 
    DEPT.DNAME AS Nama_Departemen
FROM EMP AS EMP1
JOIN DEPT 
	ON EMP1.DEPTNO = DEPT.DEPTNO
WHERE EMP1.SAL = (
    SELECT MAX(EMP2.SAL)
    FROM EMP AS EMP2
    WHERE EMP2.DEPTNO = EMP1.DEPTNO
)
ORDER BY SAL DESC;

--4
SELECT ENAME, JOB, SAL
FROM EMP
WHERE JOB <> 'CLERK' 
  AND SAL > (SELECT AVG(SAL) FROM EMP WHERE JOB = 'ANALYST');

  --5
  SELECT e.EMPNO, e.JOB, d.DNAME, e.HIREDATE
FROM EMP AS e
INNER JOIN DEPT AS d 
ON e.DEPTNO = d.DEPTNO
WHERE d.DEPTNO IN (
  SELECT DEPTNO
  FROM EMP
  WHERE JOB = 'MANAGER' AND SAL > (
    SELECT SAL
    FROM EMP
    WHERE ENAME = 'BLAKE'
  )
);

--6
SELECT e.EMPNO, e.ENAME, e.JOB, d.DNAME
FROM EMP AS e
INNER JOIN DEPT d ON e.DEPTNO = d.DEPTNO
WHERE e.JOB = 'MANAGER' OR d.DNAME = 'RESEARCH';
